addEventListener('fetch', event => event.respondWith(handleRequest(event.request)));

async function handleRequest(request) {
  const url = new URL(request.url);
  if (request.method === 'OPTIONS') return new Response(null, { status: 204, headers: corsHeaders() });
  if (url.pathname === '/widget.js') return new Response(widgetJS(), { headers: jsH() });
  return new Response(pageHTML(), { headers: htmlH() });
}

function widgetJS() {
  return "(function(){\n  if (localStorage.getItem('cookie_consent')) return;\n  var s = document.currentScript;\n  var msg = (s && s.dataset.message) || 'We use cookies to improve your experience.';\n  var pol = (s && s.dataset.policy) || '';\n  var acc = (s && s.dataset.accept) || 'Accept';\n  var dec = (s && s.dataset.decline) || 'Decline';\n  var bg = (s && s.dataset.bg) || '#111827';\n  var fg = (s && s.dataset.fg) || '#f9fafb';\n  var bar = document.createElement('div');\n  bar.style.cssText = 'position:fixed;bottom:0;left:0;right:0;z-index:99999;background:' + bg + ';color:' + fg + ';padding:14px 20px;font-family:sans-serif;font-size:13px;display:flex;flex-wrap:wrap;align-items:center;gap:10px;box-shadow:0 -2px 12px rgba(0,0,0,.3)';\n  var sp = document.createElement('span');\n  sp.innerHTML = msg + (pol ? ' <a href=\"' + pol + '\" style=\"color:#93c5fd\" target=\"_blank\" rel=\"noopener noreferrer\">Learn more</a>' : '');\n  bar.appendChild(sp);\n  var wrap = document.createElement('div');\n  wrap.style.cssText = 'margin-left:auto;display:flex;gap:8px';\n  function btn(t, bc, v){\n    var b = document.createElement('button');\n    b.textContent = t;\n    b.style.cssText = 'padding:7px 16px;border:none;border-radius:5px;cursor:pointer;font-size:13px;background:' + bc + ';color:#fff;font-weight:500';\n    b.onclick = function(){\n      localStorage.setItem('cookie_consent', v);\n      bar.remove();\n      document.dispatchEvent(new CustomEvent('cookieConsent', { detail: { action: v } }));\n    };\n    return b;\n  }\n  wrap.appendChild(btn(acc, '#1a73e8', 'accepted'));\n  wrap.appendChild(btn(dec, '#6b7280', 'declined'));\n  bar.appendChild(wrap);\n  document.body.appendChild(bar);\n})();\n";
}

function pageHTML() {
  return "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><title>Cookie Consent Banner</title>\n<style>*{box-sizing:border-box}body{font-family:system-ui,sans-serif;max-width:680px;margin:40px auto;padding:0 16px;background:#f5f7fa;color:#111827}h1{font-size:1.5rem}label{display:block;margin-top:12px;font-size:.85rem;color:#555}input{width:100%;padding:8px;margin-top:4px;border:1px solid #ccc;border-radius:6px}button{margin-top:18px;padding:10px 22px;background:#1a73e8;color:#fff;border:none;border-radius:6px;cursor:pointer}pre{background:#1e1e2e;color:#cdd6f4;padding:14px;border-radius:8px;font-size:.78rem;overflow-x:auto;margin-top:14px;display:none;white-space:pre-wrap}</style></head><body>\n<h1>Cookie Consent Banner</h1>\n<p>Create a lightweight consent prompt you can embed on any page.</p>\n<label>Message<input id=\"msg\" value=\"We use cookies to improve your experience.\"></label>\n<label>Privacy Policy URL<input id=\"pol\" placeholder=\"https://example.com/privacy\"></label>\n<label>Accept text<input id=\"acc\" value=\"Accept\"></label>\n<label>Decline text<input id=\"dec\" value=\"Decline\"></label>\n<label>Background<input id=\"bg\" type=\"color\" value=\"#111827\" style=\"height:38px\"></label>\n<label>Text color<input id=\"fg\" type=\"color\" value=\"#f9fafb\" style=\"height:38px\"></label>\n<button onclick=\"gen()\">Generate Embed Code</button>\n<pre id=\"code\"></pre>\n<script>\nfunction esc(v){ return String(v).replace(/&/g,'&amp;').replace(/\"/g,'&quot;'); }\nfunction gen(){\n  var base = location.origin;\n  var attrs = [\n    ' data-message=\"' + esc(document.getElementById('msg').value) + '\"',\n    ' data-policy=\"' + esc(document.getElementById('pol').value) + '\"',\n    ' data-accept=\"' + esc(document.getElementById('acc').value) + '\"',\n    ' data-decline=\"' + esc(document.getElementById('dec').value) + '\"',\n    ' data-bg=\"' + esc(document.getElementById('bg').value) + '\"',\n    ' data-fg=\"' + esc(document.getElementById('fg').value) + '\"'\n  ].join('');\n  var code = '<script src=\"' + base + '/widget.js\"' + attrs + '><\\/script>';\n  var pre = document.getElementById('code');\n  pre.textContent = code;\n  pre.style.display = 'block';\n}\n</script>\n</body></html>\n";
}

function corsHeaders() { return { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET,POST,OPTIONS', 'Access-Control-Allow-Headers': 'Content-Type' }; }
function htmlH() { return { ...corsHeaders(), 'Content-Type': 'text/html;charset=UTF-8' }; }
function jsH() { return { ...corsHeaders(), 'Content-Type': 'application/javascript;charset=UTF-8' }; }
