addEventListener('fetch', event => event.respondWith(handleRequest(event.request)));

async function handleRequest(request) {
  const url = new URL(request.url);
  if (request.method === 'OPTIONS') return new Response(null, { status: 204, headers: corsHeaders() });
  if (url.pathname === '/widget.js') return new Response(widgetJS(), { headers: jsH() });
  return new Response(pageHTML(), { headers: htmlH() });
}

function widgetJS() {
  return "(function(){\n  var s = document.currentScript;\n  var raw = (s && s.dataset.langs) || '[{\"code\":\"en\",\"label\":\"English\",\"url\":\"/\"}]';\n  var langs = [];\n  try { langs = JSON.parse(raw); } catch (error) { langs = [{ code: 'en', label: 'English', url: '/' }]; }\n  var current = (s && s.dataset.current) || document.documentElement.lang || 'en';\n  var pos = (s && s.dataset.position) || 'top-right';\n  var wrap = document.createElement('div');\n  var v = pos.indexOf('top') >= 0 ? 'top:12px;' : 'bottom:12px;';\n  var h = pos.indexOf('right') >= 0 ? 'right:12px;' : 'left:12px;';\n  wrap.style.cssText = 'position:fixed;' + v + h + 'z-index:99998;font-family:sans-serif;font-size:13px';\n  var sel = document.createElement('select');\n  sel.style.cssText = 'padding:6px 10px;border-radius:6px;border:1px solid #ccc;background:#fff;cursor:pointer;font-size:13px;box-shadow:0 2px 6px rgba(0,0,0,.1)';\n  langs.forEach(function(l){\n    var o = document.createElement('option');\n    o.value = l.url;\n    o.textContent = ((l.flag || '') + ' ' + l.label).trim();\n    if (l.code === current) o.selected = true;\n    sel.appendChild(o);\n  });\n  sel.onchange = function(){ if (this.value) location.href = this.value; };\n  wrap.appendChild(sel);\n  document.body.appendChild(wrap);\n})();\n";
}

function pageHTML() {
  return "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><title>Language Switcher Embed</title>\n<style>*{box-sizing:border-box}body{font-family:system-ui,sans-serif;max-width:720px;margin:40px auto;padding:0 16px;background:#f5f7fa;color:#111827}h1{font-size:1.5rem}label{display:block;margin-top:12px;font-size:.85rem;color:#555}textarea,input,select{width:100%;padding:8px;margin-top:4px;border:1px solid #ccc;border-radius:6px;font-family:ui-monospace,monospace;font-size:.85rem}button{margin-top:18px;padding:10px 22px;background:#1a73e8;color:#fff;border:none;border-radius:6px;cursor:pointer}pre{background:#1e1e2e;color:#cdd6f4;padding:14px;border-radius:8px;font-size:.78rem;overflow-x:auto;margin-top:14px;display:none;white-space:pre-wrap}</style></head><body>\n<h1>Language Switcher Embed</h1>\n<p>Generate a script tag that renders a floating language selector on your site.</p>\n<label>Languages JSON<textarea id=\"langs\" rows=\"6\">[\n  {\"code\":\"en\",\"label\":\"English\",\"url\":\"/\",\"flag\":\"\ud83c\uddfa\ud83c\uddf8\"},\n  {\"code\":\"es\",\"label\":\"Espa\u00f1ol\",\"url\":\"/es\",\"flag\":\"\ud83c\uddea\ud83c\uddf8\"},\n  {\"code\":\"fr\",\"label\":\"Fran\u00e7ais\",\"url\":\"/fr\",\"flag\":\"\ud83c\uddeb\ud83c\uddf7\"}\n]</textarea></label>\n<label>Current language code<input id=\"cur\" value=\"en\"></label>\n<label>Position<select id=\"pos\"><option value=\"top-right\">Top Right</option><option value=\"top-left\">Top Left</option><option value=\"bottom-right\">Bottom Right</option><option value=\"bottom-left\">Bottom Left</option></select></label>\n<button onclick=\"gen()\">Generate Embed Code</button>\n<pre id=\"code\"></pre>\n<script>\nfunction attrSafe(value){ return String(value).replace(/&/g,'&amp;').replace(/\"/g,'&quot;').replace(/\\s+/g,' '); }\nfunction gen(){\n  var base = location.origin;\n  var langs = attrSafe(document.getElementById('langs').value);\n  var current = attrSafe(document.getElementById('cur').value);\n  var position = attrSafe(document.getElementById('pos').value);\n  var code = '<script src=\"' + base + '/widget.js\" data-langs=\"' + langs + '\" data-current=\"' + current + '\" data-position=\"' + position + '\"><\\/script>';\n  var pre = document.getElementById('code');\n  pre.textContent = code;\n  pre.style.display = 'block';\n}\n</script>\n</body></html>\n";
}

function corsHeaders() { return { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET,POST,OPTIONS', 'Access-Control-Allow-Headers': 'Content-Type' }; }
function htmlH() { return { ...corsHeaders(), 'Content-Type': 'text/html;charset=UTF-8' }; }
function jsH() { return { ...corsHeaders(), 'Content-Type': 'application/javascript;charset=UTF-8' }; }
